# Generated by Django 5.0.7 on 2024-07-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobapp1', '0002_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
